// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal() {
  return window['go']['board']['Service']['CloseTerminal']();
}

export function Config() {
  return window['go']['board']['Service']['Config']();
}

export function Connect(arg1) {
  return window['go']['board']['Service']['Connect'](arg1);
}

export function Delete(arg1) {
  return window['go']['board']['Service']['Delete'](arg1);
}

export function Disconnect() {
  return window['go']['board']['Service']['Disconnect']();
}

export function Download(arg1, arg2) {
  return window['go']['board']['Service']['Download'](arg1, arg2);
}

export function ExportCommands() {
  return window['go']['board']['Service']['ExportCommands']();
}

export function ImportCommands() {
  return window['go']['board']['Service']['ImportCommands']();
}

export function ListCommands() {
  return window['go']['board']['Service']['ListCommands']();
}

export function ListDir(arg1) {
  return window['go']['board']['Service']['ListDir'](arg1);
}

export function PickLocalFile() {
  return window['go']['board']['Service']['PickLocalFile']();
}

export function PickSaveTarget(arg1) {
  return window['go']['board']['Service']['PickSaveTarget'](arg1);
}

export function ReadTerminal() {
  return window['go']['board']['Service']['ReadTerminal']();
}

export function ResetCommands() {
  return window['go']['board']['Service']['ResetCommands']();
}

export function RunCommand(arg1) {
  return window['go']['board']['Service']['RunCommand'](arg1);
}

export function RunCommandInTerminal(arg1) {
  return window['go']['board']['Service']['RunCommandInTerminal'](arg1);
}

export function SaveCommands(arg1) {
  return window['go']['board']['Service']['SaveCommands'](arg1);
}

export function StartTerminal() {
  return window['go']['board']['Service']['StartTerminal']();
}

export function Status() {
  return window['go']['board']['Service']['Status']();
}

export function Upload(arg1, arg2, arg3) {
  return window['go']['board']['Service']['Upload'](arg1, arg2, arg3);
}

export function WriteTerminal(arg1) {
  return window['go']['board']['Service']['WriteTerminal'](arg1);
}
