// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {board} from '../models';

export function CloseTerminal():Promise<void>;

export function Config():Promise<board.Settings>;

export function Connect(arg1:board.Device):Promise<board.Status>;

export function Delete(arg1:string):Promise<void>;

export function Disconnect():Promise<board.Status>;

export function Download(arg1:string,arg2:string):Promise<void>;

export function ExportCommands():Promise<string>;

export function ImportCommands():Promise<board.CommandFileResult>;

export function ListCommands():Promise<board.CommandList>;

export function ListDir(arg1:string):Promise<Array<board.Entry>>;

export function PickKeyFile():Promise<string>;

export function PickLocalFile():Promise<string>;

export function PickSaveTarget(arg1:string):Promise<string>;

export function ReadRemoteText(arg1:string):Promise<string>;

export function ReadTerminal():Promise<string>;

export function ResetCommands():Promise<board.CommandList>;

export function RunCommand(arg1:string):Promise<board.CommandResult>;

export function RunCommandInTerminal(arg1:string):Promise<void>;

export function SaveCommands(arg1:Array<board.Command>):Promise<board.CommandList>;

export function StartTerminal():Promise<void>;

export function Status():Promise<board.Status>;

export function Upload(arg1:string,arg2:string,arg3:boolean):Promise<board.UploadResult>;

export function WriteTerminal(arg1:string):Promise<void>;
