// Code generated by tools/genmodules; DO NOT EDIT.
// profile: all

import m_board from '../modules/board/module'
import m_netcfg from '../modules/netcfg/module'
import m_ping from '../modules/ping/module'
import m_remote from '../modules/remote/module'

export const enabledModules = [m_board, m_netcfg, m_ping, m_remote]
