// Code generated by tools/genmodules; DO NOT EDIT.
// profile: netcfg-ping-remote

import m_netcfg from '../modules/netcfg/module'
import m_ping from '../modules/ping/module'
import m_remote from '../modules/remote/module'

export const enabledModules = [m_netcfg, m_ping, m_remote]
