// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Host():Promise<string>;

export function SaveHost(arg1:string):Promise<void>;
