// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Host() {
  return window['go']['toolbox']['Service']['Host']();
}

export function SaveHost(arg1) {
  return window['go']['toolbox']['Service']['SaveHost'](arg1);
}
