// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ping} from '../models';

export function LocalIfaces():Promise<Array<ping.LocalIface>>;

export function ReadPing():Promise<ping.PingLog>;

export function Scan(arg1:string):Promise<ping.ScanResult>;

export function StartPing(arg1:string):Promise<void>;

export function StopPing():Promise<void>;
