// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LocalIfaces() {
  return window['go']['ping']['Service']['LocalIfaces']();
}

export function ReadPing() {
  return window['go']['ping']['Service']['ReadPing']();
}

export function Scan(arg1) {
  return window['go']['ping']['Service']['Scan'](arg1);
}

export function StartPing(arg1) {
  return window['go']['ping']['Service']['StartPing'](arg1);
}

export function StopPing() {
  return window['go']['ping']['Service']['StopPing']();
}
