// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {netcfg} from '../models';

export function ApplyConfig(arg1:netcfg.Device,arg2:netcfg.Config):Promise<void>;

export function ApplyWifi(arg1:netcfg.Device,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function Defaults():Promise<netcfg.Settings>;

export function GetWifiAp(arg1:netcfg.Device):Promise<netcfg.WifiAp>;

export function ListPorts(arg1:netcfg.Device):Promise<Array<netcfg.Port>>;

export function RestoreNetwork(arg1:netcfg.Device):Promise<void>;

export function TestConnection(arg1:netcfg.Device):Promise<void>;
