// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {netcfg} from '../models';

export function ApplyConfig(arg1:netcfg.Device,arg2:netcfg.Config):Promise<void>;

export function Defaults():Promise<netcfg.Settings>;

export function ListPorts(arg1:netcfg.Device):Promise<Array<netcfg.Port>>;

export function RestoreNetwork(arg1:netcfg.Device):Promise<void>;

export function TestConnection(arg1:netcfg.Device):Promise<void>;
