// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyConfig(arg1, arg2) {
  return window['go']['netcfg']['Service']['ApplyConfig'](arg1, arg2);
}

export function ApplyWifi(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['netcfg']['Service']['ApplyWifi'](arg1, arg2, arg3, arg4, arg5);
}

export function Defaults() {
  return window['go']['netcfg']['Service']['Defaults']();
}

export function GetWifiAp(arg1) {
  return window['go']['netcfg']['Service']['GetWifiAp'](arg1);
}

export function ListPorts(arg1) {
  return window['go']['netcfg']['Service']['ListPorts'](arg1);
}

export function RestoreNetwork(arg1) {
  return window['go']['netcfg']['Service']['RestoreNetwork'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['netcfg']['Service']['TestConnection'](arg1);
}
