// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {remote} from '../models';

export function Config():Promise<remote.Settings>;

export function Connect(arg1:remote.Device):Promise<remote.Status>;

export function Disconnect():Promise<remote.Status>;

export function ExportPanel(arg1:string):Promise<string>;

export function GetIO(arg1:Array<remote.IOPoint>):Promise<Array<remote.IOValue>>;

export function GetRegisters(arg1:Array<number>):Promise<Array<remote.RegisterValue>>;

export function ImportPanel(arg1:string):Promise<remote.PanelFileResult>;

export function PulseIO(arg1:remote.IOPoint,arg2:number,arg3:number,arg4:number):Promise<void>;

export function PulseRegister(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function ResetPanel(arg1:string):Promise<remote.Settings>;

export function SavePanel(arg1:remote.Tab):Promise<remote.Settings>;

export function SetIO(arg1:remote.IOPoint,arg2:number):Promise<void>;

export function SetIOForced(arg1:remote.IOPoint,arg2:boolean):Promise<void>;

export function SetIOForcedAll(arg1:Array<remote.IOPoint>,arg2:boolean):Promise<void>;

export function SetRegister(arg1:number,arg2:string):Promise<void>;

export function Status():Promise<remote.Status>;

export function ToggleIO(arg1:remote.IOPoint,arg2:number,arg3:number):Promise<number>;

export function ToggleRegister(arg1:number,arg2:number,arg3:number):Promise<number>;
