// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Config() {
  return window['go']['remote']['Service']['Config']();
}

export function Connect(arg1) {
  return window['go']['remote']['Service']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['remote']['Service']['Disconnect']();
}

export function ExportPanel(arg1) {
  return window['go']['remote']['Service']['ExportPanel'](arg1);
}

export function GetIO(arg1) {
  return window['go']['remote']['Service']['GetIO'](arg1);
}

export function GetRegisters(arg1) {
  return window['go']['remote']['Service']['GetRegisters'](arg1);
}

export function GetRobotStatus() {
  return window['go']['remote']['Service']['GetRobotStatus']();
}

export function ImportPanel(arg1) {
  return window['go']['remote']['Service']['ImportPanel'](arg1);
}

export function PulseIO(arg1, arg2, arg3, arg4) {
  return window['go']['remote']['Service']['PulseIO'](arg1, arg2, arg3, arg4);
}

export function PulseRegister(arg1, arg2, arg3, arg4) {
  return window['go']['remote']['Service']['PulseRegister'](arg1, arg2, arg3, arg4);
}

export function RebootController() {
  return window['go']['remote']['Service']['RebootController']();
}

export function ResetPanel(arg1) {
  return window['go']['remote']['Service']['ResetPanel'](arg1);
}

export function SavePanel(arg1) {
  return window['go']['remote']['Service']['SavePanel'](arg1);
}

export function SetIO(arg1, arg2) {
  return window['go']['remote']['Service']['SetIO'](arg1, arg2);
}

export function SetIOForced(arg1, arg2) {
  return window['go']['remote']['Service']['SetIOForced'](arg1, arg2);
}

export function SetIOForcedAll(arg1, arg2) {
  return window['go']['remote']['Service']['SetIOForcedAll'](arg1, arg2);
}

export function SetRegister(arg1, arg2) {
  return window['go']['remote']['Service']['SetRegister'](arg1, arg2);
}

export function Status() {
  return window['go']['remote']['Service']['Status']();
}

export function ToggleIO(arg1, arg2, arg3) {
  return window['go']['remote']['Service']['ToggleIO'](arg1, arg2, arg3);
}

export function ToggleRegister(arg1, arg2, arg3) {
  return window['go']['remote']['Service']['ToggleRegister'](arg1, arg2, arg3);
}
