// Code generated by tools/genmodules; DO NOT EDIT.
// profile: netcfg-ping-remote

package modules

import (
	"embedtools/internal/module"
	"embedtools/internal/modules/netcfg"
	"embedtools/internal/modules/ping"
	"embedtools/internal/modules/remote"
)

// All 返回当前 profile 启用的模块。
func All() []module.Module {
	return []module.Module{
		netcfg.New(),
		ping.New(),
		remote.New("command"),
	}
}
