// Code generated by tools/genmodules; DO NOT EDIT.
// profile: all

package modules

import (
	"embedtools/internal/module"
	"embedtools/internal/modules/board"
	"embedtools/internal/modules/netcfg"
	"embedtools/internal/modules/remote"
)

// All 返回当前 profile 启用的模块。
func All() []module.Module {
	return []module.Module{
		board.New(),
		netcfg.New(),
		remote.New(),
	}
}
