// Code generated by tools/genmodules; DO NOT EDIT.
// profile: 自选

package modules

import (
	"embedtools/internal/module"
	"embedtools/internal/modules/netcfg"
)

// All 返回当前 profile 启用的模块。
func All() []module.Module {
	return []module.Module{
		netcfg.New(),
	}
}
